#!/usr/bin/env bash
# Description: Apply sample AWS S3 and CloudFront Infrastructure
set -e

cd ./terraform/remote_state

aws_profile="$(terraform output aws_profile | tr -d '"' )"

cd -
cd ./terraform/infrastructure

terraform apply \
  -var "aws_profile=$aws_profile"
