#!/usr/bin/env bash
# Description: Build sample AWS S3 and Cloudfront Infrastructure
set -e

cd ./terraform/remote_state

terraform fmt
terraform init
terraform apply

tf_state_bucket_region="$(terraform output tf_state_s3_bucket_region | tr -d '"' )"
tf_state_bucket="$(terraform output tf_state_s3_bucket | tr -d '"' )"
tf_state_lock_table="$(terraform output tf_state_lock_table | tr -d '"' )"
aws_profile="$(terraform output aws_profile | tr -d '"' )"
tf_state_key="aws-s3-utf-8-content-disposition.tfstate"

cd -
cd ./terraform/infrastructure

terraform fmt
terraform init \
  -backend-config "region=$tf_state_bucket_region" \
  -backend-config "bucket=$tf_state_bucket" \
  -backend-config "dynamodb_table=$tf_state_lock_table" \
  -backend-config "profile=$aws_profile" \
  -backend-config "key=$tf_state_key" \

terraform apply \
  -var "aws_profile=$aws_profile"
